name: verigo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dio: ^3.0.7
  provider: ^4.3.2+3
  skeleton_text: ^1.0.0
  cached_network_image: ^2.5.0
  font_awesome_flutter: ^8.11.0
  google_maps_flutter: ^1.2.0
  flutter_easyloading: ^2.2.2
  adaptive_dialog: ^0.9.3
  google_sign_in: ^4.5.9
  code_fields: ^0.0.2
  flutter_snake_navigationbar: ^0.4.4
  dotted_border: ^1.0.7
  flutter_multi_formatter: ^1.3.6
  hive: ^1.4.4+1
  path_provider: ^1.6.27
  page_view_indicators: ^1.4.1
  pinput: ^1.0.0
  country_state_city_picker: ^1.2.7
  intl: ^0.16.1
  jiffy: ^3.0.1
  cupertino_tabbar: ^1.1.1
  timer_count_down: ^1.0.4+1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_polyline_points: ^0.2.4
  geolocator: ^6.2.1
  location: ^3.2.4
  google_maps_place_picker: ^1.0.1



dev_dependencies:
  hive_generator: ^0.8.2
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: fonts/LeagueSpartan-Regular.ttf
        - asset: fonts/LeagueSpartan-Light.ttf
          weight: 300
        - asset: fonts/LeagueSpartan-Medium.ttf
          weight: 400
        - asset: fonts/LeagueSpartan-Bold.ttf
          weight: 600
        - asset: fonts/LeagueSpartan-SemiBold.ttf
          weight: 500  
        - asset: fonts/LeagueSpartan-ExtraBold.ttf
          weight: 700  
        - asset: fonts/LeagueSpartan-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
